### ISSUE TITLE
Voiced Dialogue

### ISSUE THREAD

**Issue by owenslo** [Berea-CS-Courses/capstone-project-owenslo#13]
This issue is to help track the completion of voiced dialogue for this project.

**Comment by jazzij** [comment]
Is this what you showed in the report out on 4/22 ? Which screenshots are linked to this (to link a commit to an issue just add the number to the commit description or pull request (i.e. "#13 added ryle dialogue options")

**Comment by owenslo** [comment]
This is for specifically voiced dialogue. I have not done any voices for the characters yet.
